camunda.bpm:
  admin-user:
    id: demo
    password: demo
  client:
    base-url: http://localhost:8080/engine-rest # The URL pointing to the Camunda Platform Runtime REST API
    async-response-timeout: 1000 # Defines the maximum duration of the long-polling request
    worker-id: spring-boot-client # Identifies the worker towards the Engine
    #      basic-auth: # Configure if REST API is secured with basic authentication
    #        username: my-username
    #        password: my-password
    subscriptions:
      fraudInvestigation: # This topic name must match the respective `@ExternalTaskSubscription`
        lock-duration: 10000 # Defines for how long the External Tasks are locked until they can be fetched again
        process-definition-key: insurance_claim_process # Filters for External Tasks of this key
        auto-open: true # Defines whether the subscription is opened automatically or not
      claimProcessed:
        lock-duration: 10000 # Defines for how long the External Tasks are locked until they can be fetched again
        process-definition-key: insurance_claim_process # Filters for External Tasks of this key
        auto-open: false # Defines whether the subscription is opened automatically or not
      claimRejected:
        lock-duration: 10000 # Defines for how long the External Tasks are locked until they can be fetched again
        process-definition-key: insurance_claim_process # Filters for External Tasks of this key
        auto-open: false # Defines whether the subscription is opened automatically or not

logging.level.org.camunda.bpm.client: info

server:
  port : 8080